version: '2'
services: 
  database:
    image: postgres:9.5
    volumes:
      - "$PWD/docker/.data/db:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: upakaara
  app:
    build: 
      context: .
    environment:
      CONTAINER_TYPE: app
    restart: always
  redis:
    image: redis
    restart: always